# Generated by Django 2.2.5 on 2019-09-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20190921_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptuser',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.LearnableConcept'),
        ),
    ]
