# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=30, unique=True)),
                ('kd_order', models.IntegerField(blank=True, null=True)),
                ('most_used_order', models.IntegerField(blank=True, null=True)),
                ('hybrid_order', models.IntegerField(blank=True, null=True)),
                ('meaning', models.CharField(blank=True, max_length=30, null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('is_kanji', models.BooleanField(default=True)),
                ('pronunciation', models.CharField(blank=True, max_length=10, null=True)),
                ('on_yomi', models.CharField(blank=True, max_length=50, null=True)),
                ('kun_yomi', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('hiragana_equivalent', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KanjiComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_set', to='devtools.Kanji')),
                ('kanji_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_set', to='devtools.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Morphs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kanji_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtools.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('max_hybrid_order', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
