# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='kd_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='kanji',
            field=models.CharField(max_length=30),
        ),
    ]
