# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0002_auto_20160724_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanjicomponent',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='kanjicomponent',
            old_name='kanji_id',
            new_name='kanji',
        ),
        migrations.RenameField(
            model_name='morphs',
            old_name='kanji_id',
            new_name='kanji',
        ),
    ]
