# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0004_auto_20160725_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordPronunciation',
            new_name='WordFurigana',
        ),
        migrations.RenameField(
            model_name='wordfurigana',
            old_name='definition',
            new_name='furigana',
        ),
        migrations.RenameField(
            model_name='wordfurigana',
            old_name='word_id',
            new_name='word',
        ),
    ]
