# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0006_kanjiuser_level_section_sectionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
