# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0007_kanji_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionuser',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='sectionuser',
            name='section',
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='last_section_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
