# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0008_auto_20160801_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionuser',
            old_name='last_section_completed',
            new_name='current_section',
        ),
    ]
