# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0009_auto_20160801_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjiuser',
            name='example_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devtools.Words'),
        ),
        migrations.AlterField(
            model_name='kanjiuser',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
