# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0010_auto_20160806_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='proper_noun',
            field=models.BooleanField(default=False),
        ),
    ]
