# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0011_words_proper_noun'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('max_hybrid_order', models.IntegerField(blank=True, null=True)),
                ('word_ranking', models.IntegerField(blank=True, null=True)),
                ('definition', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
