# Generated by Django 2.2.5 on 2019-10-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanji',
            options={'ordering': ['popularity']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['popularity']},
        ),
        migrations.AddField(
            model_name='word',
            name='useful',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='learnableconcept',
            name='type',
            field=models.CharField(choices=[('kanji', 'kanji'), ('word', 'word')], max_length=12),
        ),
    ]
