# Generated by Django 2.2.5 on 2019-10-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20191008_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['pronunciation']},
        ),
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
