# Generated by Django 2.2.5 on 2019-10-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20191014_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
